---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
spec:
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
  type: LoadBalancer
